import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        justifyContent:'center',
        alignItems:'center',
        paddingTop:30,
        marginBottom:20,
    },
    avatar:{
        maxHeight:100,
        maxWidth:100,
        borderRadius:50,
        justifyContent:'center',
        alignItems:'center',
        marginBottom:10
    },
    name:{
        fontFamily:'BebasNeue-Regular',
        fontSize:24,
        fontWeight:'normal',
        letterSpacing:1,
        color:'#000000'
    },
    mainView:{
        padding:20,
        flex:1,
    },
    rowView:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginBottom:20
    },
    dataView:{
        justifyContent:'center',
        alignItems:'center',
        width:'50%'
    },
    outterText:{
        fontFamily:'Roboto-Medium',
        fontSize:18,
        fontWeight:'normal',
        paddingBottom:5,
        color:'#000000'
    },
    innerText:{
        fontFamily:'Roboto-Regular',
        fontSize:14,
        fontWeight:'300',
        color:'#000000'
    },
    boxView:{
        backgroundColor:'#ECECEC',
        width:'90%',
        height:50,
        borderRadius:10,
        borderWidth:1,
        borderColor:'#AA3FA6',
        justifyContent:'center',
        alignItems:'center'
    },
    bottomView:{
        justifyContent:'center',
        alignItems:'center',
        width:'100%'
    },
    bottomBox:{
        backgroundColor:'#ECECEC',
        padding:10,
        height:50,
        minWidth:'30%',
        borderRadius:10,
        borderWidth:1,
        borderColor:'#AA3FA6',
        justifyContent:'center',
        alignItems:'center',
    },
})